import Map, { GeolocateControl } from "react-map-gl";
import Post, { PostI } from '@/components/Post'

import Head from 'next/head'

const samplePost: PostI = {
  title: 'Sample Post Title',
  description: `
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
  `,
  type: 0,
  address: 'Some random address 123',
  user: {
    firstName: 'Joe',
    lastName: 'Doe',
    profile: ''
  },
  imagesURL: ['https://picsum.photos/1000/200', 'https://picsum.photos/300', 'https://picsum.photos/300', 'https://picsum.photos/300', 'https://picsum.photos/300'],
  tags: ['tag1', 'tag2']
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Posts - Helpet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex w-full h-full">
          <div className="w-[50%] h-screen items-center justify-center p-10 overflow-y-scroll">
            <div className="mx-auto">
              <div className="flex flex-row flex-wrap gap-[30px]">
                {
                  [1, 2, 3, 4].map(() => (
                    <Post { ...samplePost } />
                  ))
                }
              </div>
            </div>
          </div>
          <div className="w-[50%]">
            <Map
              mapboxAccessToken="pk.eyJ1IjoiYW5nZWxyb2RybyIsImEiOiJYWVBkNW5BIn0.68ICmtXGkzTi_wM5LN3liQ"
              initialViewState={{
                longitude: -100,
                latitude: 40,
                zoom: 3.5,
              }}
              mapStyle="mapbox://styles/mapbox/streets-v11"
            >
              <GeolocateControl
                positionOptions={{ enableHighAccuracy: true }}
                trackUserLocation={true}
              />
            </Map>
          </div>
        </div>
        <footer className="flex fixed bg-[#404040] h-[40px] bottom-0 z-50 w-full">
        </footer>
      </main>
    </>
  )
}
